name: /l Daily Runs
run-name: ${{ github.actor }} is triggering all daily scripts
on: 
  schedule:
    - cron: 30 2 * * *
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ¬ beginning DAILY runs"
      - run: echo "ğŸ‰ The job was triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the scripts directory
        run: |
          ls ${{ github.workspace }}/runners/daily
      - run: echo "ğŸ This job's status is ${{ job.status }}."
