name: /l Daily Runs
run-name: ${{ github.actor }} is triggering all daily scripts
on: 
  schedule:
    - cron: 30 2 * * *
  workflow_dispatch:
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ¬ beginning DAILY runs"
      - run: echo "ğŸ‰ The job was triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
        Option 1
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: 'pipenv'
      - name: List files in the scripts directory and run sequentially from home dir using abspath.
        run: |
          JOBS=$(find ${{ github.workspace }}/runners/daily -name "*.sh" -o -name "*.py" -not -iname "_*" -executable | sort)
          echo $JOBS
          for J in $JOBS; do
            echo "RUNNNING $J";
            pushd ${{ github.workspace }}; $J; popd
          done
      - run: echo "ğŸ This job's status is ${{ job.status }}."
